import type {
  InferGetServerSidePropsType,
  InferGetStaticPropsType,
} from "next";
import Head from "next/head";
import MiniSearch from "minisearch";
import ListOfGroups from "../../components/groups/ListOfGroups";
import Layout from "../../components/_shared/Layout";
import { CKAN } from "@portaljs/ckan";
import { useState } from "react";
import TopBar from "../../components/_shared/TopBar";
import SearchHero from "../../components/dataset/_shared/SearchHero";
import { Group } from "@portaljs/ckan";
import useSWR, { SWRConfig, unstable_serialize } from "swr";

export async function getStaticProps() {
  const ckan = new CKAN("https://demo.dev.datopian.com");
  const groups = await ckan.getGroupsWithDetails();

  return {
    props: {
      fallback: {
        [unstable_serialize(["groups"])]: groups,
      },
    },
    revalidate: 1800,
  };
}

export default function GroupsPage({
  fallback,
}: InferGetStaticPropsType<typeof getStaticProps>): JSX.Element {
  return (
    <SWRConfig value={{ fallback }}>
      <Groups />
    </SWRConfig>
  );
}
function Groups(): JSX.Element {
  const { data: groups } = useSWR(["groups"], async () => {
    const ckan = new CKAN("https://demo.dev.datopian.com");
    return await ckan.getGroupsWithDetails();
  });
  const miniSearch = new MiniSearch({
    fields: ["description", "display_name"], // fields to index for full-text search
    storeFields: ["description", "display_name", "image_display_url", "name"], // fields to return with search results
  });
  miniSearch.addAll(groups);
  return (
    <>
      <Head>
        <title>Ckan Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main miniSearch={miniSearch} groups={groups} />
    </>
  );
}

function Main({
  miniSearch,
  groups,
}: {
  miniSearch: MiniSearch<any>;
  groups: Array<Group>;
}) {
  const [searchString, setSearchString] = useState("");
  return (
    <Layout>
      <section className="row-start-1 row-end-3 col-span-full">
        <div
          className="bg-cover h-full bg-center bg-no-repeat bg-black flex flex-col"
          style={{
            backgroundImage: "url('/images/backgrounds/SearchHero.avif')",
          }}
        >
          <TopBar />
          <SearchHero
            title="Groups"
            searchValue={searchString}
            onChange={setSearchString}
          />
        </div>
      </section>
      <main className="custom-container py-8">
        <ListOfGroups
          groups={groups}
          searchString={searchString}
          miniSearch={miniSearch}
        />
      </main>
    </Layout>
  );
}
