import { GetStaticProps, InferGetStaticPropsType } from "next";
import Head from "next/head";
import getConfig from "next/config";
import DatasetInfo from "@/components/dataset/individualPage/DatasetInfo";
import DatasetOverview from "@/components/dataset/individualPage/DatasetOverview";
import DatasetNavCrumbs from "@/components/dataset/individualPage/NavCrumbs";
import ResourcesList from "@/components/dataset/individualPage/ResourcesList";
import ActivityStream from "@/components/_shared/ActivityStream";
import Layout from "@/components/_shared/Layout";
import Tabs from "@/components/_shared/Tabs";
import TopBar from "@/components/_shared/TopBar";
import { Dataset as DatasetType } from "@portaljs/ckan";
import { CKAN } from "@portaljs/ckan";
import styles from "styles/DatasetInfo.module.scss";
import {
  getAvailableOrgs,
  privateToPublicDatasetName,
  privateToPublicOrgName,
  publicToPrivateDatasetName,
} from "@/lib/queries/utils";
import { getDataset } from "@/lib/queries/dataset";
import HeroSection from "@/components/_shared/HeroSection";

export async function getStaticPaths() {
  const ckan = new CKAN(process.env.NEXT_PUBLIC_DMS);
  const mainOrg = process.env.NEXT_PUBLIC_ORG;
  const availableOrgs = await getAvailableOrgs(mainOrg);
  const paths = (
    await ckan.getDatasetsListWithDetails({ offset: 0, limit: 1000 })
  )
    //Only create routes for datasets whose owner_orgs is in the availableOrgs list
    .filter((dataset) => availableOrgs.includes(dataset.organization.name))
    .map((dataset: DatasetType) => ({
      params: {
        dataset: privateToPublicDatasetName(dataset.name, mainOrg),
        org: privateToPublicOrgName(dataset.organization?.name, mainOrg),
      },
    }));
  return {
    paths,
    fallback: "blocking",
  };
}

export const getStaticProps: GetStaticProps = async (context) => {
  try {
    const ckan = new CKAN(process.env.NEXT_PUBLIC_DMS);
    const mainOrg = process.env.NEXT_PUBLIC_ORG;
    const datasetName = context.params?.dataset as string;
    const privateDatasetName = publicToPrivateDatasetName(datasetName, mainOrg);

    if (!datasetName) {
      return {
        notFound: true,
      };
    }
    let dataset = await getDataset({ name: datasetName as string });
    if (!dataset) {
      return {
        notFound: true,
      };
    }
    const activityStream = await ckan.getDatasetActivityStream(
      privateDatasetName
    );
    dataset = {
      ...dataset,
      activity_stream: activityStream,
    };
    return {
      props: {
        dataset,
      },
      revalidate: 1800,
    };
  } catch {
    return {
      notFound: true,
    };
  }
};

export default function DatasetPage({
  dataset,
}: InferGetStaticPropsType<typeof getStaticProps>): JSX.Element {
  const tabs = [
    {
      id: "resources",
      content: (
        <ResourcesList
          resources={dataset?.resources}
          orgName={dataset.organization ? dataset.organization.name : ""}
          datasetName={dataset.name}
        />
      ),
      title: "Resources",
    },
    {
      id: "information",
      content: <DatasetOverview dataset={dataset} />,
      title: "Info",
    },
    {
      id: "activity-stream",
      content: (
        <ActivityStream
          activities={dataset?.activity_stream ? dataset.activity_stream : []}
        />
      ),
      title: "Activity Stream",
    },
  ];
  return (
    <>
      <Head>
        <title>{`${dataset.title || dataset.name} - Dataset`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <HeroSection title={dataset.title} cols="6" />
        <DatasetNavCrumbs
          org={{
            name: dataset.organization?.name,
            title: dataset.organization?.title,
          }}
          dataset={{
            name: dataset.name,
            title: dataset.title ? dataset.title : "This dataset",
          }}
        />
        <div className="grid grid-rows-datasetpage-hero mt-8">
          <section className="grid row-start-2 row-span-2 col-span-full">
            <div className="custom-container">
              {dataset && (
                <main className={styles.main}>
                  <DatasetInfo dataset={dataset} />
                  <div>
                    <Tabs items={tabs} />
                  </div>
                </main>
              )}
            </div>
          </section>
        </div>
      </Layout>
    </>
  );
}
